### ISSUE TITLE
No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package

### ISSUE THREAD

**Issue by agdestine** [fk128/ct-slice-detection#4]
Hi,
Using Mac OS. with Python 3.8, Python 3.8.6rc1 (v3.8.6rc1:08bd63da6e, Sep  7 2020, 16:14:12)
Packages version: keras-preprocessing-1.1.2 tensorboard-2.3.0 tensorflow-2.3.0 tensorflow-estimator-2.3.0

I have the following error:

Archanges-MBP:ct-slice-detection-master archangegiscarddestine$ python3 /Library/Frameworks/Python.framework/Versions/3.8/bin/l3_detect_tester --config /Users/archangegiscarddestine/Documents/ct-slice-detection-master/configs/slice_detect_1d.cfg
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/l3_detect_tester", line 33, in <module>
    sys.exit(load_entry_point('ct-slice-detection', 'console_scripts', 'l3_detect_tester')())
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/l3_detect_tester", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/archangegiscarddestine/Documents/ct-slice-detection-master/ct_slice_detection/tester.py", line 2, in <module>
    from keras.backend.tensorflow_backend import set_session
ModuleNotFoundError: No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package

Any guidance will be appreciated. Thanks in advance.

Archange

**Comment by fk128** [comment]
Please see https://github.com/fk128/sarcopenia-ai and use docker
